### ISSUE TITLE
failed to download modules: exec: "go"

### ISSUE THREAD

**Issue by fschuch** [benmatselby/hugo-deploy-gh-pages#38]
Hi,

I've been using this action for a while, following the [Tutorial](https://www.jameswright.xyz/post/deploy-hugo-academic-using-githubio/). But after updating to a newer version of Wowchemy, I'm getting this error:

```
Error: failed to download modules: exec: "go": executable file not found in $PATH
```

I tried to install go in many different ways, for instance:

```
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
```

But the error persists.

Do you have any idea about how to solve it?
